apiVersion : apps/v1
kind: Deployment
metadata:
  name: aksriv03aks1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aksriv03aks1
  template:
    metadata:
      labels:
        app: aksriv03aks1
    spec:
      containers:
        - name: aksriv03aks1
          image: aksriv03arc.azurecr.io/aksriv03aks1
          ports:
          - containerPort: 80