apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kodeypetest-729c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kodeypetest-729c"
  template:
    metadata:
      labels:
        app: "kodeypetest-729c"
    spec:
      containers:
        - name: "kodeypetest-729c"
          image: "kodeypetest1.azurecr.io/kodeypetest"
          ports:
          - containerPort: 80