apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kodeypetest"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kodeypetest"
  template:
    metadata:
      labels:
        app: "kodeypetest"
    spec:
      containers:
        - name: "kodeypetest"
          image: "nginx"
          ports:
          - containerPort: 80