apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "akskodey-8650"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "akskodey-8650"
    spec:
      containers:
        - name: "akskodey-8650"
          image: "kodeyacr.azurecr.io/akskodey"
          ports:
          - containerPort: 80