apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kodeypetest-4963"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kodeypetest-4963"
  template:
    metadata:
      labels:
        app: "kodeypetest-4963"
    spec:
      containers:
        - name: "kodeypetest-4963"
          image: "kodeypetestacr.azurecr.io/kodeypetest"
          ports:
          - containerPort: 80