apiVersion: v1
kind: Service
metadata:
    name: aksriv03aks1
    labels:
        app: aksriv03aks1
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: aksriv03aks1