apiVersion: v1
kind: Service
metadata:
    name: "kodeypetest-4963"
    labels:
        app: "kodeypetest-4963"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kodeypetest-4963"