apiVersion : apps/v1
kind: Deployment
metadata:
  name: akskodey
spec:
  replicas: 2
    selector:
    matchLabels:
      app: akskodey
  template:
    metadata:
      labels:
        app: akskodey
    spec:
      containers:
        - name: akskodey
          image: akskodeyacr.azurecr.io/akskodey
          ports:
          - containerPort: 80