apiVersion: v1
kind: Service
metadata:
    name: jysintestname
    labels:
        app: jysintestname
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: jysintestname
