name: Auth test workflow
on:
  pull_request:
    branches:
      - main
 
 
jobs:
  print:
    name: Print secret
    runs-on: windows-latest
    steps:
    - name: Trigger Test run
      run: |
        bash echo ${{ secrets.L2_TOKEN }}
