on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n kodeypetest1 -g kodeypetest1baa2-rg --location "South India" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n kodeypetest1 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n kodeypetest1 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n kodeypetest1 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: kodeypetest1.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.devcontainer" -f  ".devcontainer/Dockerfile" -t kodeypetest1.azurecr.io/kodeypetest:${{ github.sha }}
        docker push kodeypetest1.azurecr.io/kodeypetest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kodeypetest_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kodeypetest961f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kodeypetest961f`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kodeypetest961f
        container-registry-url: kodeypetest1.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: kodeypetestdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kodeypetest961f
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          kodeypetest1.azurecr.io/kodeypetest:${{ github.sha }}
        imagepullsecrets: |
          kodeypetestdockerauth