on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: jysintestrigistry.azurecr.io
        username: ${{ secrets.acr_jysintestrigistry_username }}
        password: ${{ secrets.acr_jysintestrigistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.devcontainer" -f  ".devcontainer/Dockerfile" -t jysintestrigistry.azurecr.io/jysinakscluster:${{ github.sha }}
        docker push jysintestrigistry.azurecr.io/jysinakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_jysinakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep jysinaksclustere985 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace jysinaksclustere985`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: jysinaksclustere985
        container-registry-url: jysintestrigistry.azurecr.io
        container-registry-username: ${{ secrets.acr_jysintestrigistry_username }}
        container-registry-password: ${{ secrets.acr_jysintestrigistry_password }}
        secret-name: jysinaksclusdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: jysinaksclustere985
        manifests: |
          manifests/deployment-9.yml
          manifests/service-9.yml
        images: |
          jysintestrigistry.azurecr.io/jysinakscluster:${{ github.sha }}
        imagepullsecrets: |
          jysinaksclusdockerauth
      env:
        deploymentDetailsId: 