on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: jysintestregistry.azurecr.io
        username: ${{ secrets.acr_jysintestregistry_username }}
        password: ${{ secrets.acr_jysintestregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.devcontainer" -f  ".devcontainer/Dockerfile" -t jysintestregistry.azurecr.io/jysinaks2:${{ github.sha }}
        docker push jysintestregistry.azurecr.io/jysinaks2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_jysinaks2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep jysintestns1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace jysintestns1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: jysintestns1
        container-registry-url: jysintestregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_jysintestregistry_username }}
        container-registry-password: ${{ secrets.acr_jysintestregistry_password }}
        secret-name: jysinaks2dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: jysintestns1
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          jysintestregistry.azurecr.io/jysinaks2:${{ github.sha }}
        imagepullsecrets: |
          jysinaks2dockerauth