on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kodeypetest_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kodeypetest99e1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kodeypetest99e1`
        fi

       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kodeypetest99e1
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: nginx