on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: akskodeyacr.azurecr.io
        username: ${{ secrets.acr_akskodeyacr_username }}
        password: ${{ secrets.acr_akskodeyacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.devcontainer" -f  ".devcontainer/Dockerfile" -t akskodeyacr.azurecr.io/jysinakscluster:${{ github.sha }}
        docker push akskodeyacr.azurecr.io/jysinakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_jysinakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep jysintestns1 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace jysintestns1`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: jysintestns1
        container-registry-url: akskodeyacr.azurecr.io
        container-registry-username: ${{ secrets.acr_akskodeyacr_username }}
        container-registry-password: ${{ secrets.acr_akskodeyacr_password }}
        secret-name: jysinaksclusdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: jysintestns1
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          akskodeyacr.azurecr.io/jysinakscluster:${{ github.sha }}
        imagepullsecrets: |
          jysinaksclusdockerauth