on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: jysintestregistry.azurecr.io
        username: ${{ secrets.acr_jysintestregistry_username }}
        password: ${{ secrets.acr_jysintestregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t jysintestregistry.azurecr.io/jysinaks1:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push jysintestregistry.azurecr.io/jysinaks1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_jysinaks1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep jysinaks1c7f2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace jysinaks1c7f2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: jysinaks1c7f2
        container-registry-url: jysintestregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_jysintestregistry_username }}
        container-registry-password: ${{ secrets.acr_jysintestregistry_password }}
        secret-name: jysinaks1dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: jysinaks1c7f2
        manifests: |
          manifests/deployment-20.yml
          manifests/service-20.yml
        images: |
          jysintestregistry.azurecr.io/jysinaks1:${{ github.sha }}
        imagepullsecrets: |
          jysinaks1dockerauth
