on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kodeypetest_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kodeypetest961f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kodeypetest961f`
        fi


       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kodeypetest961f
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: nginx
