on: [push]
  
jobs:
  build-and-deploy:
    env:
      REGISTRY_URL: jysintestregistry.azurecr.io
      NAMESPACE: jysintestns1
      IMAGE_NAME: jysinTestImage
      SECRET_NAME: jysinTestImage

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
   
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aksKodey_7582a }}
      id: login
    
    - name: Create namespace g
      run: |
        namespacePresent=`kubectl get namespace | grep $NAMESPACE | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace $NAMESPACE`
        fi
            
    - uses: Josh-01/k8s-deploy@releases/v1.4
      with:
        namespace: ${{ env.NAMESPACE  }}
        imagepullsecrets: demo-k8s-secret
        manifests: |
          .devcontainer/manifests/deployment.yml
          .devcontainer/manifests/service.yml
        images: |
          jysintestregistry.azurecr.io/jysintestimage:first
