on: [push]
env:
  dockerfilePaths: ''
  REGISTRY_URL: jysintestregistry.azurecr.io
  NAMESPACE: jysintestns1
  IMAGE_NAME: jysinTestImage
  SECRET_NAME: jysinTestImage
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: jysintestregistry.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    
    - name: Build and push Docker images
      id: docker_build
      uses: Josh-01/build-push-action@users/jysin/AddImageInspect
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        #file: # optional, default is ./Dockerfile
        # List of metadata for an image
        #labels: # optional
        # List of tags
        tags: |
          jysintestregistry.azurecr.io/jysintestimage:first
          jysintestregistry.azurecr.io/jysintestimage:${{ github.sha }}
        # Load is a shorthand for --output=type=docker
        #load: true
        # Push is a shorthand for --output=type=registry
        push: true
        # List of output destinations (format: type=local,dest=path)
        #outputs: # optional
  
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aksKodey_7582a }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep $NAMESPACE | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace $NAMESPACE`
        fi
            
    - uses: Josh-01/k8s-deploy@releases/v1.3
      with:
        namespace: ${{ env.NAMESPACE  }}
        manifests: |
          .devcontainer/manifests/deployment.yml
          .devcontainer/manifests/service.yml
        images: |
          jysintestregistry.azurecr.io/jysintestimage:first
        
  
    - name: Dockerfile path
      run: |
        echo ${{ env.dockerfilePaths }}
        docker image inspect jysintestregistry.azurecr.io/jysintestimage:first
