on: [push]
env:
  dockerfilePaths: ''
  
jobs:
  build-and-deploy:
    env:
      REGISTRY_URL: jysintestregistry.azurecr.io
      NAMESPACE: jysintestns1
      IMAGE_NAME: jysinTestImage
      SECRET_NAME: jysinTestImage

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: jysintestregistry.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
            
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.devcontainer" -f  ".devcontainer/Dockerfile" -t jysintestregistry.azurecr.io/jysintestimage:${{ github.sha }} 
        docker push jysintestregistry.azurecr.io/jysintestimage:${{ github.sha }}
  
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
   
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aksKodey_7582a }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep $NAMESPACE | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace $NAMESPACE`
        fi
            
    - uses: Josh-01/k8s-deploy@releases/v1.4
      with:
        namespace: ${{ env.NAMESPACE  }}
        imagepullsecrets: demo-k8s-secret
        manifests: |
          .devcontainer/manifests/deployment.yml
          .devcontainer/manifests/service.yml
        images: |
          jysintestregistry.azurecr.io/jysintestimage@${{ steps.docker_build.outputs.digest }}
