on: [push]

jobs:
  build-and-deploy:
    env:
      REGISTRY_URL: jysintestregistry.azurecr.io
      
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Run script
      run: |
        npm install @azure/event-hubs
        npm install @azure/storage-blob
        npm install @azure/eventhubs-checkpointstore-blob
        node send.js
