on: [push]
  
jobs:
  build-and-deploy:
    env:
      REGISTRY_URL: jysintestregistry.azurecr.io
      NAMESPACE: jysintestns1
      CR_USERNAME: ${{ secrets.AZURE_CLIENT_ID }}
      CR_PASSWORD: ${{ secrets.AZURE_CLIENT_SECRET }}
      HELM_CHART_PATHS: |
        ./helmChart

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
   
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aksKodey_7582a }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep $NAMESPACE | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace $NAMESPACE`
        fi
    
    - uses: Azure/k8s-create-secret@v1
      with:
        namespace: ${{ env.NAMESPACE  }}
        container-registry-url: jysintestregistry.azurecr.io
        container-registry-username: ${{ secrets.AZURE_CLIENT_ID }}
        container-registry-password: ${{ secrets.AZURE_CLIENT_SECRET }}
        secret-name: demo-k8s-secret
            
    - uses: Josh-01/k8s-deploy@releases/v1.2
      with:
        namespace: ${{ env.NAMESPACE  }}
        imagepullsecrets: demo-k8s-secret
        manifests: |
          .devcontainer/manifests/deployment.yml
          .devcontainer/manifests/service.yml
        images: |
          jysintestregistry.azurecr.io/jysintestimage:first
