on: [push]
env:
    REGISTRY_URL: jysintestregistry.azurecr.io
    NAMESPACE: jysindemo-ns2
    REGISTRY_CREDENTIALS: |
        jysintestregistry.azurecr.io ${{secrets.AZURE_CLIENT_ID}} ${{secrets.AZURE_CLIENT_SECRET}}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.AKS_JYSINAKS2_KUBECONFIG }}
      id: login
    
    - name: Create namespace actions
      run: |
        namespacePresent=`kubectl get namespace | grep $NAMESPACE | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace $NAMESPACE`
        fi
    
    - uses: Azure/k8s-create-secret@v1
      with:
        namespace: ${{ env.NAMESPACE  }}
        container-registry-url: ${{ env.REGISTRY_URL }}
        container-registry-username: ${{ secrets.AZURE_CLIENT_ID }}
        container-registry-password: ${{ secrets.AZURE_CLIENT_SECRET }}
        secret-name: demo-k8s-secret
            
    - uses: Azure/k8s-deploy@users/jysin/ConfigFilePathsAddition1_3
      with:
        namespace: ${{ env.NAMESPACE  }}
        imagepullsecrets: demo-k8s-secret
        manifests: |
          .devcontainer/manifests/deployment.yml
          .devcontainer/manifests/service.yml
        images: |
          jysintestregistry.azurecr.io/jysindemoimage:first
