on: [push]
  
jobs:
  build-and-deploy:
    env:
      NAMESPACE: jysindemo-ns3
      REGISTRY_URL_1: jysintestregistry.azurecr.io
      REGISTRY_USERNAME_1: ${{ secrets.AZURE_CLIENT_ID }}
      REGISTRY_PASSWORD_1: ${{ secrets.AZURE_CLIENT_SECRET }}
      IMAGE_NAME_1: jysintestregistry.azurecr.io/jysindemoimage:${{ github.sha }}

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY_URL_1 }}
        username: ${{ env.REGISTRY_USERNAME_1 }}
        password: ${{ env.REGISTRY_PASSWORD_1 }}
    
    - name: Build and push Docker images
      id: docker_build
      uses: Josh-01/build-push-action@AddDockerfilePathToImageLabel
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # List of tags
        tags: |
          jysintestregistry.azurecr.io/jysindemoimage:first
          ${{ env.IMAGE_NAME_1 }}
        push: true
        trace-data: true  
   
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.AKS_JYSINAKS2_KUBECONFIG }}
      id: login
    
    - name: Create namespace s
      run: |
        namespacePresent=`kubectl get namespace | grep $NAMESPACE | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace $NAMESPACE`
        fi
    
    - uses: Azure/k8s-create-secret@v1
      with:
        namespace: ${{ env.NAMESPACE  }}
        container-registry-url: ${{ env.REGISTRY_URL_1 }}
        container-registry-username: ${{ env.REGISTRY_USERNAME_1 }}
        container-registry-password: ${{ env.REGISTRY_PASSWORD_1 }}
        secret-name: demo-k8s-secret
            
    - uses: Azure/k8s-deploy@users/jysin/ConfigFilePathsAddition1_3
      with:
        namespace: ${{ env.NAMESPACE }}
        imagepullsecrets: demo-k8s-secret
        manifests: |
          .devcontainer/manifests/deployment.yml
          .devcontainer/manifests/service.yml
        images: |
          ${{ env.IMAGE_NAME_1 }}
