on: [push]
env:
    REGISTRY_URL: jysintestregistry.azurecr.io
    NAMESPACE: jysindemo-ns7
    CR_USERNAME: ${{ secrets.AZURE_CLIENT_ID }}
    CR_PASSWORD: ${{ secrets.AZURE_CLIENT_SECRET }}
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY_URL }}
        username: ${{ env.CR_USERNAME }}
        password: ${{ env.CR_PASSWORD }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.AKS_JYSINAKS2_KUBECONFIG }}
      id: login
    
    - name: Create namespace s
      run: |
        namespacePresent=`kubectl get namespace | grep $NAMESPACE | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace $NAMESPACE`
        fi
    
    - uses: Azure/k8s-create-secret@v1
      with:
        namespace: ${{ env.NAMESPACE  }}
        container-registry-url: ${{ env.REGISTRY_URL }}
        container-registry-username: ${{ env.CR_USERNAME }}
        container-registry-password: ${{ env.CR_PASSWORD }}
        secret-name: demo-k8s-secret
        
    - uses: azure/k8s-bake@feature/traceabilityChanges
      with:
        renderEngine: 'helm'
        helmChart: './helmcharts/' 
        overrides: |     
          replicas:2
        helm-version: 'latest' 
        silent: false 
      id: bake
            
    - uses: Azure/k8s-deploy@v1.3
      with:
        namespace: ${{ env.NAMESPACE }}
        imagepullsecrets: demo-k8s-secret
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          jysintestregistry.azurecr.io/jysindemoimage:first
